IF OBJECT_ID('FI_SP_PesqBeneficiario') IS NOT NULL
DROP PROCEDURE FI_SP_PesqBeneficiario

GO

CREATE PROC FI_SP_PesqBeneficiario	
	@CPF VARCHAR(15)
AS
BEGIN
	

	SELECT  B.ID, B.NOME, B.CPF, B.IDCLIENTE
		FROM BENEFICIARIOS B WITH(NOLOCK) 
		JOIN CLIENTES C WITH(NOLOCK) ON  C.ID = B.IDCLIENTE
		WHERE C.CPF = @CPF
				

	SELECT COUNT(1) FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF
END