
IF OBJECT_ID('FI_SP_VerificaBeneficiario', 'P') IS NOT NULL
DROP PROCEDURE FI_SP_VerificaBeneficiario

GO

CREATE PROC FI_SP_VerificaBeneficiario
	@CPF VARCHAR(14),
	@ID BIGINT		,
	@IDCLIENTE BIGINT
AS
BEGIN
	--VERIFICA O CPF QUE NAO SEJA DO PROPROPRIO BENEFICIARIO
	--PARA PODER VALIDAR NA ALTERAÇÃO DO CADASTRO
	SELECT 1 FROM BENEFICIARIOS WHERE IDCLIENTE = @IDCLIENTE AND CPF = @CPF AND ID <> @ID
END