
IF OBJECT_ID('FI_SP_VerificaCliente', 'P') IS NOT NULL
DROP PROCEDURE FI_SP_VerificaCliente

GO

CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR(14),
	@ID BIGINT
AS
BEGIN
	--VERIFICA O CPF QUE NAO SEJA DO PROPROPRIO CLIENTE
	--PARA PODER VALIDAR NA ALTERAÇÃO DO CADASTRO
	SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND ID <> @ID
END

